@startuml
participant "controller: Controller" as A
participant "view: View" as B
participant "viewLogin: ViewLogin" as C
participant ":Utils" as D
participant "model: Inventory Manager" as E
participant "mechanicList: MechanicList" as F

A -> B: 1. menuBegin()
activate A
activate B
return
deactivate B

A -> B: 2. menuLogin()
activate B
return
deactivate B

A -> C: 3. insertCredentials()
activate C
C -> D: 3.1 getString()
activate D
return username
deactivate D
C -> D: 3.2 getString()
activate D
return password
deactivate D
C -> "mechanic: Mechanic" ** : <<verify>>
C --> A: mechanic
deactivate C
A -> F: 4. login()
activate F
return menuMechanic()
deactivate F


A -> B: 5. menuMechanic()
activate B
return 0
deactivate B
A -> F: 6.logout()
activate F
return
deactivate F
A -> B: 6. menuBegin()
activate B
return
deactivate B

@enduml