@startuml
actor Gerente
participant Sistema


Gerente -> Sistema: 1. Remove um material ao inventário
Sistema -> Sistema: 1.1 Verifica se existe esse material no inventário
Sistema --> Gerente: 1.2 O sistema mostra uma mensagem

alt Remove Material: true
     Sistema --> Gerente: Retorna mensagem de sucesso

else Remove Material: false
     Sistema --> Gerente: Retorna erro

end
@enduml