@startuml
actor Mecânico
participant Sistema


Mecânico -> Sistema: 1. O Mecânico insere a opção de ver inventário
Sistema -> Sistema: 1.1 Verifica se existe inventário
Sistema --> Mecânico: 1.2 O sistema mostra uma lista com o inventário

alt Ver inventário: true
     Sistema --> Mecânico: Retorna sucesso

else Ver inventário: false
     Sistema --> Mecânico: Retorna erro

end
@enduml